/*
 * generated by Xtext
 */
package org.obeonetwork.sirius.text.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.obeonetwork.sirius.text.services.SiriusTextDslGrammarAccess;

public class SiriusTextDslParser extends AbstractContentAssistParser {
	
	@Inject
	private SiriusTextDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.obeonetwork.sirius.text.ui.contentassist.antlr.internal.InternalSiriusTextDslParser createParser() {
		org.obeonetwork.sirius.text.ui.contentassist.antlr.internal.InternalSiriusTextDslParser result = new org.obeonetwork.sirius.text.ui.contentassist.antlr.internal.InternalSiriusTextDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSiriusFileBodyAccess().getAlternatives(), "rule__SiriusFileBody__Alternatives");
					put(grammarAccess.getLabelPositionAccess().getAlternatives(), "rule__LabelPosition__Alternatives");
					put(grammarAccess.getGradientDirectionAccess().getAlternatives(), "rule__GradientDirection__Alternatives");
					put(grammarAccess.getSiriusFileAccess().getGroup(), "rule__SiriusFile__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getDesignerAccess().getGroup(), "rule__Designer__Group__0");
					put(grammarAccess.getDesignerAccess().getGroup_3(), "rule__Designer__Group_3__0");
					put(grammarAccess.getViewpointAccess().getGroup(), "rule__Viewpoint__Group__0");
					put(grammarAccess.getViewpointAccess().getGroup_3(), "rule__Viewpoint__Group_3__0");
					put(grammarAccess.getViewpointAccess().getGroup_5(), "rule__Viewpoint__Group_5__0");
					put(grammarAccess.getViewpointAccess().getGroup_5_4(), "rule__Viewpoint__Group_5_4__0");
					put(grammarAccess.getViewpointAccess().getGroup_6(), "rule__Viewpoint__Group_6__0");
					put(grammarAccess.getViewpointAccess().getGroup_7(), "rule__Viewpoint__Group_7__0");
					put(grammarAccess.getViewpointAccess().getGroup_7_3(), "rule__Viewpoint__Group_7_3__0");
					put(grammarAccess.getViewpointAccess().getGroup_7_3_1(), "rule__Viewpoint__Group_7_3_1__0");
					put(grammarAccess.getDiagramAccess().getGroup(), "rule__Diagram__Group__0");
					put(grammarAccess.getDiagramAccess().getGroup_7(), "rule__Diagram__Group_7__0");
					put(grammarAccess.getDiagramAccess().getGroup_11(), "rule__Diagram__Group_11__0");
					put(grammarAccess.getDiagramAccess().getGroup_14(), "rule__Diagram__Group_14__0");
					put(grammarAccess.getDiagramAccess().getGroup_16(), "rule__Diagram__Group_16__0");
					put(grammarAccess.getDiagramAccess().getGroup_17(), "rule__Diagram__Group_17__0");
					put(grammarAccess.getDiagramAccess().getGroup_18(), "rule__Diagram__Group_18__0");
					put(grammarAccess.getDiagramAccess().getGroup_19(), "rule__Diagram__Group_19__0");
					put(grammarAccess.getDiagramAccess().getGroup_20(), "rule__Diagram__Group_20__0");
					put(grammarAccess.getDiagramAccess().getGroup_20_3(), "rule__Diagram__Group_20_3__0");
					put(grammarAccess.getDiagramAccess().getGroup_20_3_1(), "rule__Diagram__Group_20_3_1__0");
					put(grammarAccess.getLayerAccess().getGroup(), "rule__Layer__Group__0");
					put(grammarAccess.getLayerAccess().getGroup_4(), "rule__Layer__Group_4__0");
					put(grammarAccess.getLayerAccess().getGroup_8(), "rule__Layer__Group_8__0");
					put(grammarAccess.getLayerAccess().getGroup_8_1(), "rule__Layer__Group_8_1__0");
					put(grammarAccess.getContainerAccess().getGroup(), "rule__Container__Group__0");
					put(grammarAccess.getContainerAccess().getGroup_4(), "rule__Container__Group_4__0");
					put(grammarAccess.getContainerAccess().getGroup_9(), "rule__Container__Group_9__0");
					put(grammarAccess.getContainerAccess().getGroup_11(), "rule__Container__Group_11__0");
					put(grammarAccess.getConditionalContainerStyleDeclarationAccess().getGroup(), "rule__ConditionalContainerStyleDeclaration__Group__0");
					put(grammarAccess.getGradientAccess().getGroup(), "rule__Gradient__Group__0");
					put(grammarAccess.getGradientAccess().getGroup_9(), "rule__Gradient__Group_9__0");
					put(grammarAccess.getGradientAccess().getGroup_10(), "rule__Gradient__Group_10__0");
					put(grammarAccess.getGradientAccess().getGroup_11(), "rule__Gradient__Group_11__0");
					put(grammarAccess.getGradientAccess().getGroup_12(), "rule__Gradient__Group_12__0");
					put(grammarAccess.getGradientAccess().getGroup_13(), "rule__Gradient__Group_13__0");
					put(grammarAccess.getPaletteAccess().getGroup(), "rule__Palette__Group__0");
					put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
					put(grammarAccess.getSiriusFileAccess().getDocumentationAssignment_0(), "rule__SiriusFile__DocumentationAssignment_0");
					put(grammarAccess.getSiriusFileAccess().getNameAssignment_2(), "rule__SiriusFile__NameAssignment_2");
					put(grammarAccess.getSiriusFileAccess().getImportsAssignment_3(), "rule__SiriusFile__ImportsAssignment_3");
					put(grammarAccess.getSiriusFileAccess().getBodyAssignment_4(), "rule__SiriusFile__BodyAssignment_4");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getDesignerAccess().getDocumentationAssignment_0(), "rule__Designer__DocumentationAssignment_0");
					put(grammarAccess.getDesignerAccess().getNameAssignment_2(), "rule__Designer__NameAssignment_2");
					put(grammarAccess.getDesignerAccess().getLabelAssignment_3_1(), "rule__Designer__LabelAssignment_3_1");
					put(grammarAccess.getDesignerAccess().getViewpointsAssignment_5(), "rule__Designer__ViewpointsAssignment_5");
					put(grammarAccess.getViewpointAccess().getDocumentationAssignment_0(), "rule__Viewpoint__DocumentationAssignment_0");
					put(grammarAccess.getViewpointAccess().getNameAssignment_2(), "rule__Viewpoint__NameAssignment_2");
					put(grammarAccess.getViewpointAccess().getLabelAssignment_3_1(), "rule__Viewpoint__LabelAssignment_3_1");
					put(grammarAccess.getViewpointAccess().getModelFileExtensionsAssignment_5_3(), "rule__Viewpoint__ModelFileExtensionsAssignment_5_3");
					put(grammarAccess.getViewpointAccess().getModelFileExtensionsAssignment_5_4_1(), "rule__Viewpoint__ModelFileExtensionsAssignment_5_4_1");
					put(grammarAccess.getViewpointAccess().getIconAssignment_6_2(), "rule__Viewpoint__IconAssignment_6_2");
					put(grammarAccess.getViewpointAccess().getRepresentationsAssignment_7_3_0(), "rule__Viewpoint__RepresentationsAssignment_7_3_0");
					put(grammarAccess.getViewpointAccess().getRepresentationsAssignment_7_3_1_1(), "rule__Viewpoint__RepresentationsAssignment_7_3_1_1");
					put(grammarAccess.getDiagramAccess().getDocumentationAssignment_0(), "rule__Diagram__DocumentationAssignment_0");
					put(grammarAccess.getDiagramAccess().getInitializedAssignment_1(), "rule__Diagram__InitializedAssignment_1");
					put(grammarAccess.getDiagramAccess().getShowOnStartupAssignment_2(), "rule__Diagram__ShowOnStartupAssignment_2");
					put(grammarAccess.getDiagramAccess().getEnablePopupBarsAssignment_3(), "rule__Diagram__EnablePopupBarsAssignment_3");
					put(grammarAccess.getDiagramAccess().getMetamodelUrisAssignment_6(), "rule__Diagram__MetamodelUrisAssignment_6");
					put(grammarAccess.getDiagramAccess().getMetamodelUrisAssignment_7_1(), "rule__Diagram__MetamodelUrisAssignment_7_1");
					put(grammarAccess.getDiagramAccess().getNameAssignment_10(), "rule__Diagram__NameAssignment_10");
					put(grammarAccess.getDiagramAccess().getLabelAssignment_11_1(), "rule__Diagram__LabelAssignment_11_1");
					put(grammarAccess.getDiagramAccess().getDomainClassAssignment_13(), "rule__Diagram__DomainClassAssignment_13");
					put(grammarAccess.getDiagramAccess().getPreconditionAssignment_14_1(), "rule__Diagram__PreconditionAssignment_14_1");
					put(grammarAccess.getDiagramAccess().getEndUserDocumentationAssignment_16_2(), "rule__Diagram__EndUserDocumentationAssignment_16_2");
					put(grammarAccess.getDiagramAccess().getTitleExpressionAssignment_17_2(), "rule__Diagram__TitleExpressionAssignment_17_2");
					put(grammarAccess.getDiagramAccess().getRootExpressionAssignment_18_2(), "rule__Diagram__RootExpressionAssignment_18_2");
					put(grammarAccess.getDiagramAccess().getDefaultLayerAssignment_19_2(), "rule__Diagram__DefaultLayerAssignment_19_2");
					put(grammarAccess.getDiagramAccess().getAdditionalLayersAssignment_20_3_0(), "rule__Diagram__AdditionalLayersAssignment_20_3_0");
					put(grammarAccess.getDiagramAccess().getAdditionalLayersAssignment_20_3_1_1(), "rule__Diagram__AdditionalLayersAssignment_20_3_1_1");
					put(grammarAccess.getLayerAccess().getDocumentationAssignment_0(), "rule__Layer__DocumentationAssignment_0");
					put(grammarAccess.getLayerAccess().getNameAssignment_2(), "rule__Layer__NameAssignment_2");
					put(grammarAccess.getLayerAccess().getIconAssignment_4_2(), "rule__Layer__IconAssignment_4_2");
					put(grammarAccess.getLayerAccess().getMappingsAssignment_8_0(), "rule__Layer__MappingsAssignment_8_0");
					put(grammarAccess.getLayerAccess().getMappingsAssignment_8_1_1(), "rule__Layer__MappingsAssignment_8_1_1");
					put(grammarAccess.getContainerAccess().getDocumentationAssignment_0(), "rule__Container__DocumentationAssignment_0");
					put(grammarAccess.getContainerAccess().getListAssignment_1(), "rule__Container__ListAssignment_1");
					put(grammarAccess.getContainerAccess().getNameAssignment_3(), "rule__Container__NameAssignment_3");
					put(grammarAccess.getContainerAccess().getLabelAssignment_4_1(), "rule__Container__LabelAssignment_4_1");
					put(grammarAccess.getContainerAccess().getDomainClassAssignment_6(), "rule__Container__DomainClassAssignment_6");
					put(grammarAccess.getContainerAccess().getStyleAssignment_8(), "rule__Container__StyleAssignment_8");
					put(grammarAccess.getContainerAccess().getPreconditionAssignment_9_1(), "rule__Container__PreconditionAssignment_9_1");
					put(grammarAccess.getContainerAccess().getSemanticCanditatesExpressionAssignment_11_2(), "rule__Container__SemanticCanditatesExpressionAssignment_11_2");
					put(grammarAccess.getContainerAccess().getConditionalStylesAssignment_12(), "rule__Container__ConditionalStylesAssignment_12");
					put(grammarAccess.getConditionalContainerStyleDeclarationAccess().getStyleAssignment_1(), "rule__ConditionalContainerStyleDeclaration__StyleAssignment_1");
					put(grammarAccess.getConditionalContainerStyleDeclarationAccess().getConditionalStyleExpressionAssignment_3(), "rule__ConditionalContainerStyleDeclaration__ConditionalStyleExpressionAssignment_3");
					put(grammarAccess.getGradientAccess().getDocumentationAssignment_0(), "rule__Gradient__DocumentationAssignment_0");
					put(grammarAccess.getGradientAccess().getDirectionAssignment_2(), "rule__Gradient__DirectionAssignment_2");
					put(grammarAccess.getGradientAccess().getNameAssignment_3(), "rule__Gradient__NameAssignment_3");
					put(grammarAccess.getGradientAccess().getBackgroundColorAssignment_5(), "rule__Gradient__BackgroundColorAssignment_5");
					put(grammarAccess.getGradientAccess().getForegroundColorAssignment_7(), "rule__Gradient__ForegroundColorAssignment_7");
					put(grammarAccess.getGradientAccess().getPositionAssignment_9_1(), "rule__Gradient__PositionAssignment_9_1");
					put(grammarAccess.getGradientAccess().getLabelExpressionAssignment_9_2(), "rule__Gradient__LabelExpressionAssignment_9_2");
					put(grammarAccess.getGradientAccess().getLabelColorAssignment_9_4(), "rule__Gradient__LabelColorAssignment_9_4");
					put(grammarAccess.getGradientAccess().getBorderSizeAssignment_10_3(), "rule__Gradient__BorderSizeAssignment_10_3");
					put(grammarAccess.getGradientAccess().getBorderColorAssignment_10_5(), "rule__Gradient__BorderColorAssignment_10_5");
					put(grammarAccess.getGradientAccess().getIconAssignment_11_2(), "rule__Gradient__IconAssignment_11_2");
					put(grammarAccess.getGradientAccess().getHeightAssignment_12_2(), "rule__Gradient__HeightAssignment_12_2");
					put(grammarAccess.getGradientAccess().getWidthAssignment_13_2(), "rule__Gradient__WidthAssignment_13_2");
					put(grammarAccess.getPaletteAccess().getDocumentationAssignment_0(), "rule__Palette__DocumentationAssignment_0");
					put(grammarAccess.getPaletteAccess().getNameAssignment_2(), "rule__Palette__NameAssignment_2");
					put(grammarAccess.getPaletteAccess().getColorsAssignment_4(), "rule__Palette__ColorsAssignment_4");
					put(grammarAccess.getColorAccess().getNameAssignment_1(), "rule__Color__NameAssignment_1");
					put(grammarAccess.getColorAccess().getValueAssignment_3(), "rule__Color__ValueAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.obeonetwork.sirius.text.ui.contentassist.antlr.internal.InternalSiriusTextDslParser typedParser = (org.obeonetwork.sirius.text.ui.contentassist.antlr.internal.InternalSiriusTextDslParser) parser;
			typedParser.entryRuleSiriusFile();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS" };
	}
	
	public SiriusTextDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SiriusTextDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
