/*
 * generated by Xtext
 */
package org.obeonetwork.sirius.text;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SiriusTextDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.obeonetwork.sirius.text.ui.internal.SiriusTextDslActivator.getInstance().getInjector("org.obeonetwork.sirius.text.SiriusTextDsl");
	}
	
}
