/*
 * generated by Xtext
 */
package org.obeonetwork.sirius.text.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.obeonetwork.sirius.text.ui.internal.SiriusTextDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SiriusTextDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SiriusTextDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SiriusTextDslActivator.getInstance().getInjector(SiriusTextDslActivator.ORG_OBEONETWORK_SIRIUS_TEXT_SIRIUSTEXTDSL);
	}
	
}
