/*
 * generated by Xtext
 */
package org.obeonetwork.sirius.text.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;


@Singleton
public class SiriusTextDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class SiriusFileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.SiriusFile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDocumentationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDocumentationDOCUMENTATIONTerminalRuleCall_0_0 = (RuleCall)cDocumentationAssignment_0.eContents().get(0);
		private final Keyword cPackageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameQualifiedNameParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cImportsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cImportsImportParserRuleCall_3_0 = (RuleCall)cImportsAssignment_3.eContents().get(0);
		private final Assignment cBodyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBodySiriusFileBodyParserRuleCall_4_0 = (RuleCall)cBodyAssignment_4.eContents().get(0);
		
		//SiriusFile:
		//	documentation=DOCUMENTATION?
		//	'package' name=QualifiedName
		//	imports+=Import*
		//	body=SiriusFileBody;
		@Override public ParserRule getRule() { return rule; }

		//documentation=DOCUMENTATION? 'package' name=QualifiedName imports+=Import* body=SiriusFileBody
		public Group getGroup() { return cGroup; }

		//documentation=DOCUMENTATION?
		public Assignment getDocumentationAssignment_0() { return cDocumentationAssignment_0; }

		//DOCUMENTATION
		public RuleCall getDocumentationDOCUMENTATIONTerminalRuleCall_0_0() { return cDocumentationDOCUMENTATIONTerminalRuleCall_0_0; }

		//'package'
		public Keyword getPackageKeyword_1() { return cPackageKeyword_1; }

		//name=QualifiedName
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_2_0() { return cNameQualifiedNameParserRuleCall_2_0; }

		//imports+=Import*
		public Assignment getImportsAssignment_3() { return cImportsAssignment_3; }

		//Import
		public RuleCall getImportsImportParserRuleCall_3_0() { return cImportsImportParserRuleCall_3_0; }

		//body=SiriusFileBody
		public Assignment getBodyAssignment_4() { return cBodyAssignment_4; }

		//SiriusFileBody
		public RuleCall getBodySiriusFileBodyParserRuleCall_4_0() { return cBodySiriusFileBodyParserRuleCall_4_0; }
	}

	public class SiriusFileBodyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.SiriusFileBody");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDesignerParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRepresentationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLayerParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMappingParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cStyleParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cPaletteParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//SiriusFileBody:
		//	Designer | Representation | Layer | Mapping | Style | Palette;
		@Override public ParserRule getRule() { return rule; }

		//Designer | Representation | Layer | Mapping | Style | Palette
		public Alternatives getAlternatives() { return cAlternatives; }

		//Designer
		public RuleCall getDesignerParserRuleCall_0() { return cDesignerParserRuleCall_0; }

		//Representation
		public RuleCall getRepresentationParserRuleCall_1() { return cRepresentationParserRuleCall_1; }

		//Layer
		public RuleCall getLayerParserRuleCall_2() { return cLayerParserRuleCall_2; }

		//Mapping
		public RuleCall getMappingParserRuleCall_3() { return cMappingParserRuleCall_3; }

		//Style
		public RuleCall getStyleParserRuleCall_4() { return cStyleParserRuleCall_4; }

		//Palette
		public RuleCall getPaletteParserRuleCall_5() { return cPaletteParserRuleCall_5; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }

		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }

		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class QualifiedNameWithWildcardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.QualifiedNameWithWildcard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//QualifiedNameWithWildcard:
		//	QualifiedName '.*'?;
		@Override public ParserRule getRule() { return rule; }

		//QualifiedName '.*'?
		public Group getGroup() { return cGroup; }

		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }

		//'.*'?
		public Keyword getFullStopAsteriskKeyword_1() { return cFullStopAsteriskKeyword_1; }
	}

	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportedNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0 = (RuleCall)cImportedNamespaceAssignment_1.eContents().get(0);
		
		//Import:
		//	'import' importedNamespace=QualifiedNameWithWildcard;
		@Override public ParserRule getRule() { return rule; }

		//'import' importedNamespace=QualifiedNameWithWildcard
		public Group getGroup() { return cGroup; }

		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//importedNamespace=QualifiedNameWithWildcard
		public Assignment getImportedNamespaceAssignment_1() { return cImportedNamespaceAssignment_1; }

		//QualifiedNameWithWildcard
		public RuleCall getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0() { return cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0; }
	}

	public class DesignerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Designer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDocumentationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDocumentationDOCUMENTATIONTerminalRuleCall_0_0 = (RuleCall)cDocumentationAssignment_0.eContents().get(0);
		private final Keyword cDesignerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cLabelAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cLabelAssignment_3_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cViewpointsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cViewpointsViewpointParserRuleCall_5_0 = (RuleCall)cViewpointsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Designer:
		//	documentation=DOCUMENTATION?
		//	'designer' name=ID ('as' label=STRING)? '{'
		//	viewpoints+=Viewpoint*
		//	'}';
		@Override public ParserRule getRule() { return rule; }

		//documentation=DOCUMENTATION? 'designer' name=ID ('as' label=STRING)? '{' viewpoints+=Viewpoint* '}'
		public Group getGroup() { return cGroup; }

		//documentation=DOCUMENTATION?
		public Assignment getDocumentationAssignment_0() { return cDocumentationAssignment_0; }

		//DOCUMENTATION
		public RuleCall getDocumentationDOCUMENTATIONTerminalRuleCall_0_0() { return cDocumentationDOCUMENTATIONTerminalRuleCall_0_0; }

		//'designer'
		public Keyword getDesignerKeyword_1() { return cDesignerKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//('as' label=STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//'as'
		public Keyword getAsKeyword_3_0() { return cAsKeyword_3_0; }

		//label=STRING
		public Assignment getLabelAssignment_3_1() { return cLabelAssignment_3_1; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_3_1_0() { return cLabelSTRINGTerminalRuleCall_3_1_0; }

		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//viewpoints+=Viewpoint*
		public Assignment getViewpointsAssignment_5() { return cViewpointsAssignment_5; }

		//Viewpoint
		public RuleCall getViewpointsViewpointParserRuleCall_5_0() { return cViewpointsViewpointParserRuleCall_5_0; }

		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class ViewpointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Viewpoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDocumentationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDocumentationDOCUMENTATIONTerminalRuleCall_0_0 = (RuleCall)cDocumentationAssignment_0.eContents().get(0);
		private final Keyword cViewpointKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cLabelAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cLabelAssignment_3_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cModelFileExtensionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cModelFileExtensionsAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cModelFileExtensionsSTRINGTerminalRuleCall_5_3_0 = (RuleCall)cModelFileExtensionsAssignment_5_3.eContents().get(0);
		private final Group cGroup_5_4 = (Group)cGroup_5.eContents().get(4);
		private final Keyword cCommaKeyword_5_4_0 = (Keyword)cGroup_5_4.eContents().get(0);
		private final Assignment cModelFileExtensionsAssignment_5_4_1 = (Assignment)cGroup_5_4.eContents().get(1);
		private final RuleCall cModelFileExtensionsSTRINGTerminalRuleCall_5_4_1_0 = (RuleCall)cModelFileExtensionsAssignment_5_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cIconKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cEqualsSignKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cIconAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cIconSTRINGTerminalRuleCall_6_2_0 = (RuleCall)cIconAssignment_6_2.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cRepresentationsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cEqualsSignKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Assignment cRepresentationsAssignment_7_3_0 = (Assignment)cGroup_7_3.eContents().get(0);
		private final CrossReference cRepresentationsRepresentationCrossReference_7_3_0_0 = (CrossReference)cRepresentationsAssignment_7_3_0.eContents().get(0);
		private final RuleCall cRepresentationsRepresentationQualifiedNameParserRuleCall_7_3_0_0_1 = (RuleCall)cRepresentationsRepresentationCrossReference_7_3_0_0.eContents().get(1);
		private final Group cGroup_7_3_1 = (Group)cGroup_7_3.eContents().get(1);
		private final Keyword cCommaKeyword_7_3_1_0 = (Keyword)cGroup_7_3_1.eContents().get(0);
		private final Assignment cRepresentationsAssignment_7_3_1_1 = (Assignment)cGroup_7_3_1.eContents().get(1);
		private final CrossReference cRepresentationsRepresentationCrossReference_7_3_1_1_0 = (CrossReference)cRepresentationsAssignment_7_3_1_1.eContents().get(0);
		private final RuleCall cRepresentationsRepresentationQualifiedNameParserRuleCall_7_3_1_1_0_1 = (RuleCall)cRepresentationsRepresentationCrossReference_7_3_1_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Viewpoint:
		//	documentation=DOCUMENTATION?
		//	'viewpoint' name=ID ('as' label=STRING)? '{' ('modelFileExtensions' '=' '[' modelFileExtensions+=STRING (','
		//	modelFileExtensions+=STRING)* ']')? ('icon' '=' icon=STRING)? ('representations' '=' '['
		//	(representations+=[Representation|QualifiedName] (',' representations+=[Representation|QualifiedName])*)? ']')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }

		//documentation=DOCUMENTATION? 'viewpoint' name=ID ('as' label=STRING)? '{' ('modelFileExtensions' '=' '['
		//modelFileExtensions+=STRING (',' modelFileExtensions+=STRING)* ']')? ('icon' '=' icon=STRING)? ('representations' '='
		//'[' (representations+=[Representation|QualifiedName] (',' representations+=[Representation|QualifiedName])*)? ']')? '}'
		public Group getGroup() { return cGroup; }

		//documentation=DOCUMENTATION?
		public Assignment getDocumentationAssignment_0() { return cDocumentationAssignment_0; }

		//DOCUMENTATION
		public RuleCall getDocumentationDOCUMENTATIONTerminalRuleCall_0_0() { return cDocumentationDOCUMENTATIONTerminalRuleCall_0_0; }

		//'viewpoint'
		public Keyword getViewpointKeyword_1() { return cViewpointKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//('as' label=STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//'as'
		public Keyword getAsKeyword_3_0() { return cAsKeyword_3_0; }

		//label=STRING
		public Assignment getLabelAssignment_3_1() { return cLabelAssignment_3_1; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_3_1_0() { return cLabelSTRINGTerminalRuleCall_3_1_0; }

		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//('modelFileExtensions' '=' '[' modelFileExtensions+=STRING (',' modelFileExtensions+=STRING)* ']')?
		public Group getGroup_5() { return cGroup_5; }

		//'modelFileExtensions'
		public Keyword getModelFileExtensionsKeyword_5_0() { return cModelFileExtensionsKeyword_5_0; }

		//'='
		public Keyword getEqualsSignKeyword_5_1() { return cEqualsSignKeyword_5_1; }

		//'['
		public Keyword getLeftSquareBracketKeyword_5_2() { return cLeftSquareBracketKeyword_5_2; }

		//modelFileExtensions+=STRING
		public Assignment getModelFileExtensionsAssignment_5_3() { return cModelFileExtensionsAssignment_5_3; }

		//STRING
		public RuleCall getModelFileExtensionsSTRINGTerminalRuleCall_5_3_0() { return cModelFileExtensionsSTRINGTerminalRuleCall_5_3_0; }

		//(',' modelFileExtensions+=STRING)*
		public Group getGroup_5_4() { return cGroup_5_4; }

		//','
		public Keyword getCommaKeyword_5_4_0() { return cCommaKeyword_5_4_0; }

		//modelFileExtensions+=STRING
		public Assignment getModelFileExtensionsAssignment_5_4_1() { return cModelFileExtensionsAssignment_5_4_1; }

		//STRING
		public RuleCall getModelFileExtensionsSTRINGTerminalRuleCall_5_4_1_0() { return cModelFileExtensionsSTRINGTerminalRuleCall_5_4_1_0; }

		//']'
		public Keyword getRightSquareBracketKeyword_5_5() { return cRightSquareBracketKeyword_5_5; }

		//('icon' '=' icon=STRING)?
		public Group getGroup_6() { return cGroup_6; }

		//'icon'
		public Keyword getIconKeyword_6_0() { return cIconKeyword_6_0; }

		//'='
		public Keyword getEqualsSignKeyword_6_1() { return cEqualsSignKeyword_6_1; }

		//icon=STRING
		public Assignment getIconAssignment_6_2() { return cIconAssignment_6_2; }

		//STRING
		public RuleCall getIconSTRINGTerminalRuleCall_6_2_0() { return cIconSTRINGTerminalRuleCall_6_2_0; }

		//('representations' '=' '[' (representations+=[Representation|QualifiedName] (','
		//representations+=[Representation|QualifiedName])*)? ']')?
		public Group getGroup_7() { return cGroup_7; }

		//'representations'
		public Keyword getRepresentationsKeyword_7_0() { return cRepresentationsKeyword_7_0; }

		//'='
		public Keyword getEqualsSignKeyword_7_1() { return cEqualsSignKeyword_7_1; }

		//'['
		public Keyword getLeftSquareBracketKeyword_7_2() { return cLeftSquareBracketKeyword_7_2; }

		//(representations+=[Representation|QualifiedName] (',' representations+=[Representation|QualifiedName])*)?
		public Group getGroup_7_3() { return cGroup_7_3; }

		//representations+=[Representation|QualifiedName]
		public Assignment getRepresentationsAssignment_7_3_0() { return cRepresentationsAssignment_7_3_0; }

		//[Representation|QualifiedName]
		public CrossReference getRepresentationsRepresentationCrossReference_7_3_0_0() { return cRepresentationsRepresentationCrossReference_7_3_0_0; }

		//QualifiedName
		public RuleCall getRepresentationsRepresentationQualifiedNameParserRuleCall_7_3_0_0_1() { return cRepresentationsRepresentationQualifiedNameParserRuleCall_7_3_0_0_1; }

		//(',' representations+=[Representation|QualifiedName])*
		public Group getGroup_7_3_1() { return cGroup_7_3_1; }

		//','
		public Keyword getCommaKeyword_7_3_1_0() { return cCommaKeyword_7_3_1_0; }

		//representations+=[Representation|QualifiedName]
		public Assignment getRepresentationsAssignment_7_3_1_1() { return cRepresentationsAssignment_7_3_1_1; }

		//[Representation|QualifiedName]
		public CrossReference getRepresentationsRepresentationCrossReference_7_3_1_1_0() { return cRepresentationsRepresentationCrossReference_7_3_1_1_0; }

		//QualifiedName
		public RuleCall getRepresentationsRepresentationQualifiedNameParserRuleCall_7_3_1_1_0_1() { return cRepresentationsRepresentationQualifiedNameParserRuleCall_7_3_1_1_0_1; }

		//']'
		public Keyword getRightSquareBracketKeyword_7_4() { return cRightSquareBracketKeyword_7_4; }

		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class RepresentationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Representation");
		private final RuleCall cDiagramParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Representation:
		//	Diagram;
		@Override public ParserRule getRule() { return rule; }

		//Diagram
		public RuleCall getDiagramParserRuleCall() { return cDiagramParserRuleCall; }
	}

	public class DiagramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Diagram");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDocumentationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDocumentationDOCUMENTATIONTerminalRuleCall_0_0 = (RuleCall)cDocumentationAssignment_0.eContents().get(0);
		private final Assignment cInitializedAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cInitializedInitializedKeyword_1_0 = (Keyword)cInitializedAssignment_1.eContents().get(0);
		private final Assignment cShowOnStartupAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cShowOnStartupShowOnStartupKeyword_2_0 = (Keyword)cShowOnStartupAssignment_2.eContents().get(0);
		private final Assignment cEnablePopupBarsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cEnablePopupBarsEnablePopupBarsKeyword_3_0 = (Keyword)cEnablePopupBarsAssignment_3.eContents().get(0);
		private final Keyword cMetamodelUrisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cMetamodelUrisAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cMetamodelUrisSTRINGTerminalRuleCall_6_0 = (RuleCall)cMetamodelUrisAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMetamodelUrisAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMetamodelUrisSTRINGTerminalRuleCall_7_1_0 = (RuleCall)cMetamodelUrisAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cDiagramKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cNameAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cNameIDTerminalRuleCall_10_0 = (RuleCall)cNameAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cAsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cLabelAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_11_1_0 = (RuleCall)cLabelAssignment_11_1.eContents().get(0);
		private final Keyword cForKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cDomainClassAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cDomainClassSTRINGTerminalRuleCall_13_0 = (RuleCall)cDomainClassAssignment_13.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cQuestionMarkKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cPreconditionAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cPreconditionEXPRESSIONTerminalRuleCall_14_1_0 = (RuleCall)cPreconditionAssignment_14_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cDocumentationKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Keyword cEqualsSignKeyword_16_1 = (Keyword)cGroup_16.eContents().get(1);
		private final Assignment cEndUserDocumentationAssignment_16_2 = (Assignment)cGroup_16.eContents().get(2);
		private final RuleCall cEndUserDocumentationSTRINGTerminalRuleCall_16_2_0 = (RuleCall)cEndUserDocumentationAssignment_16_2.eContents().get(0);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cTitleExpressionKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Keyword cEqualsSignKeyword_17_1 = (Keyword)cGroup_17.eContents().get(1);
		private final Assignment cTitleExpressionAssignment_17_2 = (Assignment)cGroup_17.eContents().get(2);
		private final RuleCall cTitleExpressionEXPRESSIONTerminalRuleCall_17_2_0 = (RuleCall)cTitleExpressionAssignment_17_2.eContents().get(0);
		private final Group cGroup_18 = (Group)cGroup.eContents().get(18);
		private final Keyword cRootExpressionKeyword_18_0 = (Keyword)cGroup_18.eContents().get(0);
		private final Keyword cEqualsSignKeyword_18_1 = (Keyword)cGroup_18.eContents().get(1);
		private final Assignment cRootExpressionAssignment_18_2 = (Assignment)cGroup_18.eContents().get(2);
		private final RuleCall cRootExpressionEXPRESSIONTerminalRuleCall_18_2_0 = (RuleCall)cRootExpressionAssignment_18_2.eContents().get(0);
		private final Group cGroup_19 = (Group)cGroup.eContents().get(19);
		private final Keyword cDefaultLayerKeyword_19_0 = (Keyword)cGroup_19.eContents().get(0);
		private final Keyword cEqualsSignKeyword_19_1 = (Keyword)cGroup_19.eContents().get(1);
		private final Assignment cDefaultLayerAssignment_19_2 = (Assignment)cGroup_19.eContents().get(2);
		private final CrossReference cDefaultLayerLayerCrossReference_19_2_0 = (CrossReference)cDefaultLayerAssignment_19_2.eContents().get(0);
		private final RuleCall cDefaultLayerLayerQualifiedNameParserRuleCall_19_2_0_1 = (RuleCall)cDefaultLayerLayerCrossReference_19_2_0.eContents().get(1);
		private final Group cGroup_20 = (Group)cGroup.eContents().get(20);
		private final Keyword cAdditionalLayersKeyword_20_0 = (Keyword)cGroup_20.eContents().get(0);
		private final Keyword cEqualsSignKeyword_20_1 = (Keyword)cGroup_20.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_20_2 = (Keyword)cGroup_20.eContents().get(2);
		private final Group cGroup_20_3 = (Group)cGroup_20.eContents().get(3);
		private final Assignment cAdditionalLayersAssignment_20_3_0 = (Assignment)cGroup_20_3.eContents().get(0);
		private final CrossReference cAdditionalLayersLayerCrossReference_20_3_0_0 = (CrossReference)cAdditionalLayersAssignment_20_3_0.eContents().get(0);
		private final RuleCall cAdditionalLayersLayerQualifiedNameParserRuleCall_20_3_0_0_1 = (RuleCall)cAdditionalLayersLayerCrossReference_20_3_0_0.eContents().get(1);
		private final Group cGroup_20_3_1 = (Group)cGroup_20_3.eContents().get(1);
		private final Keyword cCommaKeyword_20_3_1_0 = (Keyword)cGroup_20_3_1.eContents().get(0);
		private final Assignment cAdditionalLayersAssignment_20_3_1_1 = (Assignment)cGroup_20_3_1.eContents().get(1);
		private final CrossReference cAdditionalLayersLayerCrossReference_20_3_1_1_0 = (CrossReference)cAdditionalLayersAssignment_20_3_1_1.eContents().get(0);
		private final RuleCall cAdditionalLayersLayerQualifiedNameParserRuleCall_20_3_1_1_0_1 = (RuleCall)cAdditionalLayersLayerCrossReference_20_3_1_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_20_4 = (Keyword)cGroup_20.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_21 = (Keyword)cGroup.eContents().get(21);
		
		//Diagram:
		//	documentation=DOCUMENTATION?
		//	initialized?='@Initialized'?
		//	showOnStartup?='@ShowOnStartup'?
		//	enablePopupBars?='@EnablePopupBars'?
		//	'@MetamodelUris'+ '({'
		//	metamodelUris+=STRING (',' metamodelUris+=STRING)*
		//	'})'
		//	'diagram' name=ID ('as' label=STRING)? 'for' domainClass=STRING ('?' precondition=EXPRESSION)? '{' ('documentation'
		//	'=' endUserDocumentation=STRING)? ('titleExpression' '=' titleExpression=EXPRESSION)? ('rootExpression' '='
		//	rootExpression=EXPRESSION)? ('defaultLayer' '=' defaultLayer=[Layer|QualifiedName])? ('additionalLayers' '=' '['
		//	(additionalLayers+=[Layer|QualifiedName] (',' additionalLayers+=[Layer|QualifiedName])*)?
		//	']')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }

		//documentation=DOCUMENTATION? initialized?='@Initialized'? showOnStartup?='@ShowOnStartup'?
		//enablePopupBars?='@EnablePopupBars'? '@MetamodelUris'+ '({' metamodelUris+=STRING (',' metamodelUris+=STRING)* '})'
		//'diagram' name=ID ('as' label=STRING)? 'for' domainClass=STRING ('?' precondition=EXPRESSION)? '{' ('documentation' '='
		//endUserDocumentation=STRING)? ('titleExpression' '=' titleExpression=EXPRESSION)? ('rootExpression' '='
		//rootExpression=EXPRESSION)? ('defaultLayer' '=' defaultLayer=[Layer|QualifiedName])? ('additionalLayers' '=' '['
		//(additionalLayers+=[Layer|QualifiedName] (',' additionalLayers+=[Layer|QualifiedName])*)? ']')? '}'
		public Group getGroup() { return cGroup; }

		//documentation=DOCUMENTATION?
		public Assignment getDocumentationAssignment_0() { return cDocumentationAssignment_0; }

		//DOCUMENTATION
		public RuleCall getDocumentationDOCUMENTATIONTerminalRuleCall_0_0() { return cDocumentationDOCUMENTATIONTerminalRuleCall_0_0; }

		//initialized?='@Initialized'?
		public Assignment getInitializedAssignment_1() { return cInitializedAssignment_1; }

		//'@Initialized'
		public Keyword getInitializedInitializedKeyword_1_0() { return cInitializedInitializedKeyword_1_0; }

		//showOnStartup?='@ShowOnStartup'?
		public Assignment getShowOnStartupAssignment_2() { return cShowOnStartupAssignment_2; }

		//'@ShowOnStartup'
		public Keyword getShowOnStartupShowOnStartupKeyword_2_0() { return cShowOnStartupShowOnStartupKeyword_2_0; }

		//enablePopupBars?='@EnablePopupBars'?
		public Assignment getEnablePopupBarsAssignment_3() { return cEnablePopupBarsAssignment_3; }

		//'@EnablePopupBars'
		public Keyword getEnablePopupBarsEnablePopupBarsKeyword_3_0() { return cEnablePopupBarsEnablePopupBarsKeyword_3_0; }

		//'@MetamodelUris'+
		public Keyword getMetamodelUrisKeyword_4() { return cMetamodelUrisKeyword_4; }

		//'({'
		public Keyword getLeftParenthesisLeftCurlyBracketKeyword_5() { return cLeftParenthesisLeftCurlyBracketKeyword_5; }

		//metamodelUris+=STRING
		public Assignment getMetamodelUrisAssignment_6() { return cMetamodelUrisAssignment_6; }

		//STRING
		public RuleCall getMetamodelUrisSTRINGTerminalRuleCall_6_0() { return cMetamodelUrisSTRINGTerminalRuleCall_6_0; }

		//(',' metamodelUris+=STRING)*
		public Group getGroup_7() { return cGroup_7; }

		//','
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//metamodelUris+=STRING
		public Assignment getMetamodelUrisAssignment_7_1() { return cMetamodelUrisAssignment_7_1; }

		//STRING
		public RuleCall getMetamodelUrisSTRINGTerminalRuleCall_7_1_0() { return cMetamodelUrisSTRINGTerminalRuleCall_7_1_0; }

		//'})'
		public Keyword getRightCurlyBracketRightParenthesisKeyword_8() { return cRightCurlyBracketRightParenthesisKeyword_8; }

		//'diagram'
		public Keyword getDiagramKeyword_9() { return cDiagramKeyword_9; }

		//name=ID
		public Assignment getNameAssignment_10() { return cNameAssignment_10; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_10_0() { return cNameIDTerminalRuleCall_10_0; }

		//('as' label=STRING)?
		public Group getGroup_11() { return cGroup_11; }

		//'as'
		public Keyword getAsKeyword_11_0() { return cAsKeyword_11_0; }

		//label=STRING
		public Assignment getLabelAssignment_11_1() { return cLabelAssignment_11_1; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_11_1_0() { return cLabelSTRINGTerminalRuleCall_11_1_0; }

		//'for'
		public Keyword getForKeyword_12() { return cForKeyword_12; }

		//domainClass=STRING
		public Assignment getDomainClassAssignment_13() { return cDomainClassAssignment_13; }

		//STRING
		public RuleCall getDomainClassSTRINGTerminalRuleCall_13_0() { return cDomainClassSTRINGTerminalRuleCall_13_0; }

		//('?' precondition=EXPRESSION)?
		public Group getGroup_14() { return cGroup_14; }

		//'?'
		public Keyword getQuestionMarkKeyword_14_0() { return cQuestionMarkKeyword_14_0; }

		//precondition=EXPRESSION
		public Assignment getPreconditionAssignment_14_1() { return cPreconditionAssignment_14_1; }

		//EXPRESSION
		public RuleCall getPreconditionEXPRESSIONTerminalRuleCall_14_1_0() { return cPreconditionEXPRESSIONTerminalRuleCall_14_1_0; }

		//'{'
		public Keyword getLeftCurlyBracketKeyword_15() { return cLeftCurlyBracketKeyword_15; }

		//('documentation' '=' endUserDocumentation=STRING)?
		public Group getGroup_16() { return cGroup_16; }

		//'documentation'
		public Keyword getDocumentationKeyword_16_0() { return cDocumentationKeyword_16_0; }

		//'='
		public Keyword getEqualsSignKeyword_16_1() { return cEqualsSignKeyword_16_1; }

		//endUserDocumentation=STRING
		public Assignment getEndUserDocumentationAssignment_16_2() { return cEndUserDocumentationAssignment_16_2; }

		//STRING
		public RuleCall getEndUserDocumentationSTRINGTerminalRuleCall_16_2_0() { return cEndUserDocumentationSTRINGTerminalRuleCall_16_2_0; }

		//('titleExpression' '=' titleExpression=EXPRESSION)?
		public Group getGroup_17() { return cGroup_17; }

		//'titleExpression'
		public Keyword getTitleExpressionKeyword_17_0() { return cTitleExpressionKeyword_17_0; }

		//'='
		public Keyword getEqualsSignKeyword_17_1() { return cEqualsSignKeyword_17_1; }

		//titleExpression=EXPRESSION
		public Assignment getTitleExpressionAssignment_17_2() { return cTitleExpressionAssignment_17_2; }

		//EXPRESSION
		public RuleCall getTitleExpressionEXPRESSIONTerminalRuleCall_17_2_0() { return cTitleExpressionEXPRESSIONTerminalRuleCall_17_2_0; }

		//('rootExpression' '=' rootExpression=EXPRESSION)?
		public Group getGroup_18() { return cGroup_18; }

		//'rootExpression'
		public Keyword getRootExpressionKeyword_18_0() { return cRootExpressionKeyword_18_0; }

		//'='
		public Keyword getEqualsSignKeyword_18_1() { return cEqualsSignKeyword_18_1; }

		//rootExpression=EXPRESSION
		public Assignment getRootExpressionAssignment_18_2() { return cRootExpressionAssignment_18_2; }

		//EXPRESSION
		public RuleCall getRootExpressionEXPRESSIONTerminalRuleCall_18_2_0() { return cRootExpressionEXPRESSIONTerminalRuleCall_18_2_0; }

		//('defaultLayer' '=' defaultLayer=[Layer|QualifiedName])?
		public Group getGroup_19() { return cGroup_19; }

		//'defaultLayer'
		public Keyword getDefaultLayerKeyword_19_0() { return cDefaultLayerKeyword_19_0; }

		//'='
		public Keyword getEqualsSignKeyword_19_1() { return cEqualsSignKeyword_19_1; }

		//defaultLayer=[Layer|QualifiedName]
		public Assignment getDefaultLayerAssignment_19_2() { return cDefaultLayerAssignment_19_2; }

		//[Layer|QualifiedName]
		public CrossReference getDefaultLayerLayerCrossReference_19_2_0() { return cDefaultLayerLayerCrossReference_19_2_0; }

		//QualifiedName
		public RuleCall getDefaultLayerLayerQualifiedNameParserRuleCall_19_2_0_1() { return cDefaultLayerLayerQualifiedNameParserRuleCall_19_2_0_1; }

		//('additionalLayers' '=' '[' (additionalLayers+=[Layer|QualifiedName] (',' additionalLayers+=[Layer|QualifiedName])*)?
		//']')?
		public Group getGroup_20() { return cGroup_20; }

		//'additionalLayers'
		public Keyword getAdditionalLayersKeyword_20_0() { return cAdditionalLayersKeyword_20_0; }

		//'='
		public Keyword getEqualsSignKeyword_20_1() { return cEqualsSignKeyword_20_1; }

		//'['
		public Keyword getLeftSquareBracketKeyword_20_2() { return cLeftSquareBracketKeyword_20_2; }

		//(additionalLayers+=[Layer|QualifiedName] (',' additionalLayers+=[Layer|QualifiedName])*)?
		public Group getGroup_20_3() { return cGroup_20_3; }

		//additionalLayers+=[Layer|QualifiedName]
		public Assignment getAdditionalLayersAssignment_20_3_0() { return cAdditionalLayersAssignment_20_3_0; }

		//[Layer|QualifiedName]
		public CrossReference getAdditionalLayersLayerCrossReference_20_3_0_0() { return cAdditionalLayersLayerCrossReference_20_3_0_0; }

		//QualifiedName
		public RuleCall getAdditionalLayersLayerQualifiedNameParserRuleCall_20_3_0_0_1() { return cAdditionalLayersLayerQualifiedNameParserRuleCall_20_3_0_0_1; }

		//(',' additionalLayers+=[Layer|QualifiedName])*
		public Group getGroup_20_3_1() { return cGroup_20_3_1; }

		//','
		public Keyword getCommaKeyword_20_3_1_0() { return cCommaKeyword_20_3_1_0; }

		//additionalLayers+=[Layer|QualifiedName]
		public Assignment getAdditionalLayersAssignment_20_3_1_1() { return cAdditionalLayersAssignment_20_3_1_1; }

		//[Layer|QualifiedName]
		public CrossReference getAdditionalLayersLayerCrossReference_20_3_1_1_0() { return cAdditionalLayersLayerCrossReference_20_3_1_1_0; }

		//QualifiedName
		public RuleCall getAdditionalLayersLayerQualifiedNameParserRuleCall_20_3_1_1_0_1() { return cAdditionalLayersLayerQualifiedNameParserRuleCall_20_3_1_1_0_1; }

		//']'
		public Keyword getRightSquareBracketKeyword_20_4() { return cRightSquareBracketKeyword_20_4; }

		//'}'
		public Keyword getRightCurlyBracketKeyword_21() { return cRightCurlyBracketKeyword_21; }
	}

	public class LayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Layer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDocumentationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDocumentationDOCUMENTATIONTerminalRuleCall_0_0 = (RuleCall)cDocumentationAssignment_0.eContents().get(0);
		private final Keyword cLayerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIconKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cEqualsSignKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIconAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cIconSTRINGTerminalRuleCall_4_2_0 = (RuleCall)cIconAssignment_4_2.eContents().get(0);
		private final Keyword cMappingsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Assignment cMappingsAssignment_8_0 = (Assignment)cGroup_8.eContents().get(0);
		private final CrossReference cMappingsMappingCrossReference_8_0_0 = (CrossReference)cMappingsAssignment_8_0.eContents().get(0);
		private final RuleCall cMappingsMappingQualifiedNameParserRuleCall_8_0_0_1 = (RuleCall)cMappingsMappingCrossReference_8_0_0.eContents().get(1);
		private final Group cGroup_8_1 = (Group)cGroup_8.eContents().get(1);
		private final Keyword cCommaKeyword_8_1_0 = (Keyword)cGroup_8_1.eContents().get(0);
		private final Assignment cMappingsAssignment_8_1_1 = (Assignment)cGroup_8_1.eContents().get(1);
		private final CrossReference cMappingsMappingCrossReference_8_1_1_0 = (CrossReference)cMappingsAssignment_8_1_1.eContents().get(0);
		private final RuleCall cMappingsMappingQualifiedNameParserRuleCall_8_1_1_0_1 = (RuleCall)cMappingsMappingCrossReference_8_1_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cEdgesKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cEqualsSignKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cLeftSquareBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cRightSquareBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Layer:
		//	documentation=DOCUMENTATION?
		//	'layer' name=ID '{' ('icon' '=' icon=STRING)?
		//	'mappings' '=' '[' (mappings+=[Mapping|QualifiedName] (',' mappings+=[Mapping|QualifiedName])*)?
		//	']'
		//	'edges' '=' '[' ']'
		//	'}';
		@Override public ParserRule getRule() { return rule; }

		//documentation=DOCUMENTATION? 'layer' name=ID '{' ('icon' '=' icon=STRING)? 'mappings' '=' '['
		//(mappings+=[Mapping|QualifiedName] (',' mappings+=[Mapping|QualifiedName])*)? ']' 'edges' '=' '[' ']' '}'
		public Group getGroup() { return cGroup; }

		//documentation=DOCUMENTATION?
		public Assignment getDocumentationAssignment_0() { return cDocumentationAssignment_0; }

		//DOCUMENTATION
		public RuleCall getDocumentationDOCUMENTATIONTerminalRuleCall_0_0() { return cDocumentationDOCUMENTATIONTerminalRuleCall_0_0; }

		//'layer'
		public Keyword getLayerKeyword_1() { return cLayerKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//('icon' '=' icon=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//'icon'
		public Keyword getIconKeyword_4_0() { return cIconKeyword_4_0; }

		//'='
		public Keyword getEqualsSignKeyword_4_1() { return cEqualsSignKeyword_4_1; }

		//icon=STRING
		public Assignment getIconAssignment_4_2() { return cIconAssignment_4_2; }

		//STRING
		public RuleCall getIconSTRINGTerminalRuleCall_4_2_0() { return cIconSTRINGTerminalRuleCall_4_2_0; }

		//'mappings'
		public Keyword getMappingsKeyword_5() { return cMappingsKeyword_5; }

		//'='
		public Keyword getEqualsSignKeyword_6() { return cEqualsSignKeyword_6; }

		//'['
		public Keyword getLeftSquareBracketKeyword_7() { return cLeftSquareBracketKeyword_7; }

		//(mappings+=[Mapping|QualifiedName] (',' mappings+=[Mapping|QualifiedName])*)?
		public Group getGroup_8() { return cGroup_8; }

		//mappings+=[Mapping|QualifiedName]
		public Assignment getMappingsAssignment_8_0() { return cMappingsAssignment_8_0; }

		//[Mapping|QualifiedName]
		public CrossReference getMappingsMappingCrossReference_8_0_0() { return cMappingsMappingCrossReference_8_0_0; }

		//QualifiedName
		public RuleCall getMappingsMappingQualifiedNameParserRuleCall_8_0_0_1() { return cMappingsMappingQualifiedNameParserRuleCall_8_0_0_1; }

		//(',' mappings+=[Mapping|QualifiedName])*
		public Group getGroup_8_1() { return cGroup_8_1; }

		//','
		public Keyword getCommaKeyword_8_1_0() { return cCommaKeyword_8_1_0; }

		//mappings+=[Mapping|QualifiedName]
		public Assignment getMappingsAssignment_8_1_1() { return cMappingsAssignment_8_1_1; }

		//[Mapping|QualifiedName]
		public CrossReference getMappingsMappingCrossReference_8_1_1_0() { return cMappingsMappingCrossReference_8_1_1_0; }

		//QualifiedName
		public RuleCall getMappingsMappingQualifiedNameParserRuleCall_8_1_1_0_1() { return cMappingsMappingQualifiedNameParserRuleCall_8_1_1_0_1; }

		//']'
		public Keyword getRightSquareBracketKeyword_9() { return cRightSquareBracketKeyword_9; }

		//'edges'
		public Keyword getEdgesKeyword_10() { return cEdgesKeyword_10; }

		//'='
		public Keyword getEqualsSignKeyword_11() { return cEqualsSignKeyword_11; }

		//'['
		public Keyword getLeftSquareBracketKeyword_12() { return cLeftSquareBracketKeyword_12; }

		//']'
		public Keyword getRightSquareBracketKeyword_13() { return cRightSquareBracketKeyword_13; }

		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}

	public class MappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Mapping");
		private final RuleCall cContainerParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Mapping:
		//	Container;
		@Override public ParserRule getRule() { return rule; }

		//Container
		public RuleCall getContainerParserRuleCall() { return cContainerParserRuleCall; }
	}

	public class ContainerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Container");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDocumentationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDocumentationDOCUMENTATIONTerminalRuleCall_0_0 = (RuleCall)cDocumentationAssignment_0.eContents().get(0);
		private final Assignment cListAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cListListKeyword_1_0 = (Keyword)cListAssignment_1.eContents().get(0);
		private final Keyword cContainerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLabelAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cLabelAssignment_4_1.eContents().get(0);
		private final Keyword cForKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cDomainClassAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDomainClassSTRINGTerminalRuleCall_6_0 = (RuleCall)cDomainClassAssignment_6.eContents().get(0);
		private final Keyword cStyleKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cStyleAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cStyleContainerStyleCrossReference_8_0 = (CrossReference)cStyleAssignment_8.eContents().get(0);
		private final RuleCall cStyleContainerStyleQualifiedNameParserRuleCall_8_0_1 = (RuleCall)cStyleContainerStyleCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cQuestionMarkKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cPreconditionAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cPreconditionEXPRESSIONTerminalRuleCall_9_1_0 = (RuleCall)cPreconditionAssignment_9_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cSemanticCandidatesExpressionKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cEqualsSignKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cSemanticCanditatesExpressionAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cSemanticCanditatesExpressionEXPRESSIONTerminalRuleCall_11_2_0 = (RuleCall)cSemanticCanditatesExpressionAssignment_11_2.eContents().get(0);
		private final Assignment cConditionalStylesAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cConditionalStylesConditionalContainerStyleDeclarationParserRuleCall_12_0 = (RuleCall)cConditionalStylesAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Container:
		//	documentation=DOCUMENTATION?
		//	list?='list'? 'container' name=ID ('as' label=STRING)? 'for' domainClass=STRING 'style'
		//	style=[ContainerStyle|QualifiedName] ('?' precondition=EXPRESSION)? '{' ('semanticCandidatesExpression' '='
		//	semanticCanditatesExpression=EXPRESSION)?
		//	conditionalStyles+=ConditionalContainerStyleDeclaration*
		//	'}';
		@Override public ParserRule getRule() { return rule; }

		//documentation=DOCUMENTATION? list?='list'? 'container' name=ID ('as' label=STRING)? 'for' domainClass=STRING 'style'
		//style=[ContainerStyle|QualifiedName] ('?' precondition=EXPRESSION)? '{' ('semanticCandidatesExpression' '='
		//semanticCanditatesExpression=EXPRESSION)? conditionalStyles+=ConditionalContainerStyleDeclaration* '}'
		public Group getGroup() { return cGroup; }

		//documentation=DOCUMENTATION?
		public Assignment getDocumentationAssignment_0() { return cDocumentationAssignment_0; }

		//DOCUMENTATION
		public RuleCall getDocumentationDOCUMENTATIONTerminalRuleCall_0_0() { return cDocumentationDOCUMENTATIONTerminalRuleCall_0_0; }

		//list?='list'?
		public Assignment getListAssignment_1() { return cListAssignment_1; }

		//'list'
		public Keyword getListListKeyword_1_0() { return cListListKeyword_1_0; }

		//'container'
		public Keyword getContainerKeyword_2() { return cContainerKeyword_2; }

		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }

		//('as' label=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//'as'
		public Keyword getAsKeyword_4_0() { return cAsKeyword_4_0; }

		//label=STRING
		public Assignment getLabelAssignment_4_1() { return cLabelAssignment_4_1; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_4_1_0() { return cLabelSTRINGTerminalRuleCall_4_1_0; }

		//'for'
		public Keyword getForKeyword_5() { return cForKeyword_5; }

		//domainClass=STRING
		public Assignment getDomainClassAssignment_6() { return cDomainClassAssignment_6; }

		//STRING
		public RuleCall getDomainClassSTRINGTerminalRuleCall_6_0() { return cDomainClassSTRINGTerminalRuleCall_6_0; }

		//'style'
		public Keyword getStyleKeyword_7() { return cStyleKeyword_7; }

		//style=[ContainerStyle|QualifiedName]
		public Assignment getStyleAssignment_8() { return cStyleAssignment_8; }

		//[ContainerStyle|QualifiedName]
		public CrossReference getStyleContainerStyleCrossReference_8_0() { return cStyleContainerStyleCrossReference_8_0; }

		//QualifiedName
		public RuleCall getStyleContainerStyleQualifiedNameParserRuleCall_8_0_1() { return cStyleContainerStyleQualifiedNameParserRuleCall_8_0_1; }

		//('?' precondition=EXPRESSION)?
		public Group getGroup_9() { return cGroup_9; }

		//'?'
		public Keyword getQuestionMarkKeyword_9_0() { return cQuestionMarkKeyword_9_0; }

		//precondition=EXPRESSION
		public Assignment getPreconditionAssignment_9_1() { return cPreconditionAssignment_9_1; }

		//EXPRESSION
		public RuleCall getPreconditionEXPRESSIONTerminalRuleCall_9_1_0() { return cPreconditionEXPRESSIONTerminalRuleCall_9_1_0; }

		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }

		//('semanticCandidatesExpression' '=' semanticCanditatesExpression=EXPRESSION)?
		public Group getGroup_11() { return cGroup_11; }

		//'semanticCandidatesExpression'
		public Keyword getSemanticCandidatesExpressionKeyword_11_0() { return cSemanticCandidatesExpressionKeyword_11_0; }

		//'='
		public Keyword getEqualsSignKeyword_11_1() { return cEqualsSignKeyword_11_1; }

		//semanticCanditatesExpression=EXPRESSION
		public Assignment getSemanticCanditatesExpressionAssignment_11_2() { return cSemanticCanditatesExpressionAssignment_11_2; }

		//EXPRESSION
		public RuleCall getSemanticCanditatesExpressionEXPRESSIONTerminalRuleCall_11_2_0() { return cSemanticCanditatesExpressionEXPRESSIONTerminalRuleCall_11_2_0; }

		//conditionalStyles+=ConditionalContainerStyleDeclaration*
		public Assignment getConditionalStylesAssignment_12() { return cConditionalStylesAssignment_12; }

		//ConditionalContainerStyleDeclaration
		public RuleCall getConditionalStylesConditionalContainerStyleDeclarationParserRuleCall_12_0() { return cConditionalStylesConditionalContainerStyleDeclarationParserRuleCall_12_0; }

		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class ConditionalContainerStyleDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.ConditionalContainerStyleDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStyleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cStyleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cStyleContainerStyleCrossReference_1_0 = (CrossReference)cStyleAssignment_1.eContents().get(0);
		private final RuleCall cStyleContainerStyleQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cStyleContainerStyleCrossReference_1_0.eContents().get(1);
		private final Keyword cIfKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionalStyleExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionalStyleExpressionEXPRESSIONTerminalRuleCall_3_0 = (RuleCall)cConditionalStyleExpressionAssignment_3.eContents().get(0);
		
		//ConditionalContainerStyleDeclaration:
		//	'style' style=[ContainerStyle|QualifiedName] 'if' conditionalStyleExpression=EXPRESSION;
		@Override public ParserRule getRule() { return rule; }

		//'style' style=[ContainerStyle|QualifiedName] 'if' conditionalStyleExpression=EXPRESSION
		public Group getGroup() { return cGroup; }

		//'style'
		public Keyword getStyleKeyword_0() { return cStyleKeyword_0; }

		//style=[ContainerStyle|QualifiedName]
		public Assignment getStyleAssignment_1() { return cStyleAssignment_1; }

		//[ContainerStyle|QualifiedName]
		public CrossReference getStyleContainerStyleCrossReference_1_0() { return cStyleContainerStyleCrossReference_1_0; }

		//QualifiedName
		public RuleCall getStyleContainerStyleQualifiedNameParserRuleCall_1_0_1() { return cStyleContainerStyleQualifiedNameParserRuleCall_1_0_1; }

		//'if'
		public Keyword getIfKeyword_2() { return cIfKeyword_2; }

		//conditionalStyleExpression=EXPRESSION
		public Assignment getConditionalStyleExpressionAssignment_3() { return cConditionalStyleExpressionAssignment_3; }

		//EXPRESSION
		public RuleCall getConditionalStyleExpressionEXPRESSIONTerminalRuleCall_3_0() { return cConditionalStyleExpressionEXPRESSIONTerminalRuleCall_3_0; }
	}

	public class StyleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Style");
		private final RuleCall cContainerStyleParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Style:
		//	ContainerStyle;
		@Override public ParserRule getRule() { return rule; }

		//ContainerStyle
		public RuleCall getContainerStyleParserRuleCall() { return cContainerStyleParserRuleCall; }
	}

	public class ContainerStyleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.ContainerStyle");
		private final RuleCall cGradientParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//ContainerStyle:
		//	Gradient;
		@Override public ParserRule getRule() { return rule; }

		//Gradient
		public RuleCall getGradientParserRuleCall() { return cGradientParserRuleCall; }
	}

	public class GradientElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Gradient");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDocumentationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDocumentationDOCUMENTATIONTerminalRuleCall_0_0 = (RuleCall)cDocumentationAssignment_0.eContents().get(0);
		private final Keyword cGradientKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDirectionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDirectionGradientDirectionEnumRuleCall_2_0 = (RuleCall)cDirectionAssignment_2.eContents().get(0);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cFromKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBackgroundColorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cBackgroundColorColorCrossReference_5_0 = (CrossReference)cBackgroundColorAssignment_5.eContents().get(0);
		private final RuleCall cBackgroundColorColorQualifiedNameParserRuleCall_5_0_1 = (RuleCall)cBackgroundColorColorCrossReference_5_0.eContents().get(1);
		private final Keyword cToKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cForegroundColorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cForegroundColorColorCrossReference_7_0 = (CrossReference)cForegroundColorAssignment_7.eContents().get(0);
		private final RuleCall cForegroundColorColorQualifiedNameParserRuleCall_7_0_1 = (RuleCall)cForegroundColorColorCrossReference_7_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cLabelKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cLabelAlignmentAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cLabelAlignmentLabelAlignmentEnumRuleCall_9_1_0 = (RuleCall)cLabelAlignmentAssignment_9_1.eContents().get(0);
		private final Assignment cLabelExpressionAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cLabelExpressionEXPRESSIONTerminalRuleCall_9_2_0 = (RuleCall)cLabelExpressionAssignment_9_2.eContents().get(0);
		private final Keyword cInKeyword_9_3 = (Keyword)cGroup_9.eContents().get(3);
		private final Assignment cLabelColorAssignment_9_4 = (Assignment)cGroup_9.eContents().get(4);
		private final CrossReference cLabelColorColorCrossReference_9_4_0 = (CrossReference)cLabelColorAssignment_9_4.eContents().get(0);
		private final RuleCall cLabelColorColorQualifiedNameParserRuleCall_9_4_0_1 = (RuleCall)cLabelColorColorCrossReference_9_4_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cBorderKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cSizeKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Keyword cEqualsSignKeyword_10_2 = (Keyword)cGroup_10.eContents().get(2);
		private final Assignment cBorderSizeAssignment_10_3 = (Assignment)cGroup_10.eContents().get(3);
		private final RuleCall cBorderSizeINTTerminalRuleCall_10_3_0 = (RuleCall)cBorderSizeAssignment_10_3.eContents().get(0);
		private final Keyword cInKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Assignment cBorderColorAssignment_10_5 = (Assignment)cGroup_10.eContents().get(5);
		private final CrossReference cBorderColorColorCrossReference_10_5_0 = (CrossReference)cBorderColorAssignment_10_5.eContents().get(0);
		private final RuleCall cBorderColorColorQualifiedNameParserRuleCall_10_5_0_1 = (RuleCall)cBorderColorColorCrossReference_10_5_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cIconKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cEqualsSignKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cIconAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cIconSTRINGTerminalRuleCall_11_2_0 = (RuleCall)cIconAssignment_11_2.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cHeightComputationExpressionKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cEqualsSignKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cHeightComputationExpressionAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cHeightComputationExpressionEXPRESSIONTerminalRuleCall_12_2_0 = (RuleCall)cHeightComputationExpressionAssignment_12_2.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cWidthComputationExpressionKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cEqualsSignKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Assignment cWidthComputationExpressionAssignment_13_2 = (Assignment)cGroup_13.eContents().get(2);
		private final RuleCall cWidthComputationExpressionEXPRESSIONTerminalRuleCall_13_2_0 = (RuleCall)cWidthComputationExpressionAssignment_13_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Gradient:
		//	documentation=DOCUMENTATION?
		//	'gradient' direction=GradientDirection name=ID 'from' backgroundColor=[Color|QualifiedName] 'to'
		//	foregroundColor=[Color|QualifiedName] '{' ('label' labelAlignment=LabelAlignment labelExpression=EXPRESSION 'in'
		//	labelColor=[Color|QualifiedName])? ('border' 'size' '=' borderSize=INT 'in' borderColor=[Color|QualifiedName])?
		//	('icon' '=' icon=STRING)? ('heightComputationExpression' '=' heightComputationExpression=EXPRESSION)?
		//	('widthComputationExpression' '=' widthComputationExpression=EXPRESSION)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }

		//documentation=DOCUMENTATION? 'gradient' direction=GradientDirection name=ID 'from' backgroundColor=[Color|QualifiedName]
		//'to' foregroundColor=[Color|QualifiedName] '{' ('label' labelAlignment=LabelAlignment labelExpression=EXPRESSION 'in'
		//labelColor=[Color|QualifiedName])? ('border' 'size' '=' borderSize=INT 'in' borderColor=[Color|QualifiedName])? ('icon'
		//'=' icon=STRING)? ('heightComputationExpression' '=' heightComputationExpression=EXPRESSION)?
		//('widthComputationExpression' '=' widthComputationExpression=EXPRESSION)? '}'
		public Group getGroup() { return cGroup; }

		//documentation=DOCUMENTATION?
		public Assignment getDocumentationAssignment_0() { return cDocumentationAssignment_0; }

		//DOCUMENTATION
		public RuleCall getDocumentationDOCUMENTATIONTerminalRuleCall_0_0() { return cDocumentationDOCUMENTATIONTerminalRuleCall_0_0; }

		//'gradient'
		public Keyword getGradientKeyword_1() { return cGradientKeyword_1; }

		//direction=GradientDirection
		public Assignment getDirectionAssignment_2() { return cDirectionAssignment_2; }

		//GradientDirection
		public RuleCall getDirectionGradientDirectionEnumRuleCall_2_0() { return cDirectionGradientDirectionEnumRuleCall_2_0; }

		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }

		//'from'
		public Keyword getFromKeyword_4() { return cFromKeyword_4; }

		//backgroundColor=[Color|QualifiedName]
		public Assignment getBackgroundColorAssignment_5() { return cBackgroundColorAssignment_5; }

		//[Color|QualifiedName]
		public CrossReference getBackgroundColorColorCrossReference_5_0() { return cBackgroundColorColorCrossReference_5_0; }

		//QualifiedName
		public RuleCall getBackgroundColorColorQualifiedNameParserRuleCall_5_0_1() { return cBackgroundColorColorQualifiedNameParserRuleCall_5_0_1; }

		//'to'
		public Keyword getToKeyword_6() { return cToKeyword_6; }

		//foregroundColor=[Color|QualifiedName]
		public Assignment getForegroundColorAssignment_7() { return cForegroundColorAssignment_7; }

		//[Color|QualifiedName]
		public CrossReference getForegroundColorColorCrossReference_7_0() { return cForegroundColorColorCrossReference_7_0; }

		//QualifiedName
		public RuleCall getForegroundColorColorQualifiedNameParserRuleCall_7_0_1() { return cForegroundColorColorQualifiedNameParserRuleCall_7_0_1; }

		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }

		//('label' labelAlignment=LabelAlignment labelExpression=EXPRESSION 'in' labelColor=[Color|QualifiedName])?
		public Group getGroup_9() { return cGroup_9; }

		//'label'
		public Keyword getLabelKeyword_9_0() { return cLabelKeyword_9_0; }

		//labelAlignment=LabelAlignment
		public Assignment getLabelAlignmentAssignment_9_1() { return cLabelAlignmentAssignment_9_1; }

		//LabelAlignment
		public RuleCall getLabelAlignmentLabelAlignmentEnumRuleCall_9_1_0() { return cLabelAlignmentLabelAlignmentEnumRuleCall_9_1_0; }

		//labelExpression=EXPRESSION
		public Assignment getLabelExpressionAssignment_9_2() { return cLabelExpressionAssignment_9_2; }

		//EXPRESSION
		public RuleCall getLabelExpressionEXPRESSIONTerminalRuleCall_9_2_0() { return cLabelExpressionEXPRESSIONTerminalRuleCall_9_2_0; }

		//'in'
		public Keyword getInKeyword_9_3() { return cInKeyword_9_3; }

		//labelColor=[Color|QualifiedName]
		public Assignment getLabelColorAssignment_9_4() { return cLabelColorAssignment_9_4; }

		//[Color|QualifiedName]
		public CrossReference getLabelColorColorCrossReference_9_4_0() { return cLabelColorColorCrossReference_9_4_0; }

		//QualifiedName
		public RuleCall getLabelColorColorQualifiedNameParserRuleCall_9_4_0_1() { return cLabelColorColorQualifiedNameParserRuleCall_9_4_0_1; }

		//('border' 'size' '=' borderSize=INT 'in' borderColor=[Color|QualifiedName])?
		public Group getGroup_10() { return cGroup_10; }

		//'border'
		public Keyword getBorderKeyword_10_0() { return cBorderKeyword_10_0; }

		//'size'
		public Keyword getSizeKeyword_10_1() { return cSizeKeyword_10_1; }

		//'='
		public Keyword getEqualsSignKeyword_10_2() { return cEqualsSignKeyword_10_2; }

		//borderSize=INT
		public Assignment getBorderSizeAssignment_10_3() { return cBorderSizeAssignment_10_3; }

		//INT
		public RuleCall getBorderSizeINTTerminalRuleCall_10_3_0() { return cBorderSizeINTTerminalRuleCall_10_3_0; }

		//'in'
		public Keyword getInKeyword_10_4() { return cInKeyword_10_4; }

		//borderColor=[Color|QualifiedName]
		public Assignment getBorderColorAssignment_10_5() { return cBorderColorAssignment_10_5; }

		//[Color|QualifiedName]
		public CrossReference getBorderColorColorCrossReference_10_5_0() { return cBorderColorColorCrossReference_10_5_0; }

		//QualifiedName
		public RuleCall getBorderColorColorQualifiedNameParserRuleCall_10_5_0_1() { return cBorderColorColorQualifiedNameParserRuleCall_10_5_0_1; }

		//('icon' '=' icon=STRING)?
		public Group getGroup_11() { return cGroup_11; }

		//'icon'
		public Keyword getIconKeyword_11_0() { return cIconKeyword_11_0; }

		//'='
		public Keyword getEqualsSignKeyword_11_1() { return cEqualsSignKeyword_11_1; }

		//icon=STRING
		public Assignment getIconAssignment_11_2() { return cIconAssignment_11_2; }

		//STRING
		public RuleCall getIconSTRINGTerminalRuleCall_11_2_0() { return cIconSTRINGTerminalRuleCall_11_2_0; }

		//('heightComputationExpression' '=' heightComputationExpression=EXPRESSION)?
		public Group getGroup_12() { return cGroup_12; }

		//'heightComputationExpression'
		public Keyword getHeightComputationExpressionKeyword_12_0() { return cHeightComputationExpressionKeyword_12_0; }

		//'='
		public Keyword getEqualsSignKeyword_12_1() { return cEqualsSignKeyword_12_1; }

		//heightComputationExpression=EXPRESSION
		public Assignment getHeightComputationExpressionAssignment_12_2() { return cHeightComputationExpressionAssignment_12_2; }

		//EXPRESSION
		public RuleCall getHeightComputationExpressionEXPRESSIONTerminalRuleCall_12_2_0() { return cHeightComputationExpressionEXPRESSIONTerminalRuleCall_12_2_0; }

		//('widthComputationExpression' '=' widthComputationExpression=EXPRESSION)?
		public Group getGroup_13() { return cGroup_13; }

		//'widthComputationExpression'
		public Keyword getWidthComputationExpressionKeyword_13_0() { return cWidthComputationExpressionKeyword_13_0; }

		//'='
		public Keyword getEqualsSignKeyword_13_1() { return cEqualsSignKeyword_13_1; }

		//widthComputationExpression=EXPRESSION
		public Assignment getWidthComputationExpressionAssignment_13_2() { return cWidthComputationExpressionAssignment_13_2; }

		//EXPRESSION
		public RuleCall getWidthComputationExpressionEXPRESSIONTerminalRuleCall_13_2_0() { return cWidthComputationExpressionEXPRESSIONTerminalRuleCall_13_2_0; }

		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}

	public class PaletteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Palette");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDocumentationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDocumentationDOCUMENTATIONTerminalRuleCall_0_0 = (RuleCall)cDocumentationAssignment_0.eContents().get(0);
		private final Keyword cPaletteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cColorsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cColorsColorParserRuleCall_4_0 = (RuleCall)cColorsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Palette:
		//	documentation=DOCUMENTATION?
		//	'palette' name=ID '{'
		//	colors+=Color*
		//	'}';
		@Override public ParserRule getRule() { return rule; }

		//documentation=DOCUMENTATION? 'palette' name=ID '{' colors+=Color* '}'
		public Group getGroup() { return cGroup; }

		//documentation=DOCUMENTATION?
		public Assignment getDocumentationAssignment_0() { return cDocumentationAssignment_0; }

		//DOCUMENTATION
		public RuleCall getDocumentationDOCUMENTATIONTerminalRuleCall_0_0() { return cDocumentationDOCUMENTATIONTerminalRuleCall_0_0; }

		//'palette'
		public Keyword getPaletteKeyword_1() { return cPaletteKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//colors+=Color*
		public Assignment getColorsAssignment_4() { return cColorsAssignment_4; }

		//Color
		public RuleCall getColorsColorParserRuleCall_4_0() { return cColorsColorParserRuleCall_4_0; }

		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class ColorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.Color");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueColorValueParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//Color:
		//	'color' name=ID '=' value=ColorValue;
		@Override public ParserRule getRule() { return rule; }

		//'color' name=ID '=' value=ColorValue
		public Group getGroup() { return cGroup; }

		//'color'
		public Keyword getColorKeyword_0() { return cColorKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//value=ColorValue
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }

		//ColorValue
		public RuleCall getValueColorValueParserRuleCall_3_0() { return cValueColorValueParserRuleCall_3_0; }
	}

	public class ColorValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.ColorValue");
		private final RuleCall cRGBParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//ColorValue:
		//	RGB;
		@Override public ParserRule getRule() { return rule; }

		//RGB
		public RuleCall getRGBParserRuleCall() { return cRGBParserRuleCall; }
	}

	public class RGBElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.RGB");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRgbKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRedAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRedINTTerminalRuleCall_1_0 = (RuleCall)cRedAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cGreenAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cGreenINTTerminalRuleCall_3_0 = (RuleCall)cGreenAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBlueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBlueINTTerminalRuleCall_5_0 = (RuleCall)cBlueAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//RGB:
		//	'rgb(' red=INT ',' green=INT ',' blue=INT ')';
		@Override public ParserRule getRule() { return rule; }

		//'rgb(' red=INT ',' green=INT ',' blue=INT ')'
		public Group getGroup() { return cGroup; }

		//'rgb('
		public Keyword getRgbKeyword_0() { return cRgbKeyword_0; }

		//red=INT
		public Assignment getRedAssignment_1() { return cRedAssignment_1; }

		//INT
		public RuleCall getRedINTTerminalRuleCall_1_0() { return cRedINTTerminalRuleCall_1_0; }

		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }

		//green=INT
		public Assignment getGreenAssignment_3() { return cGreenAssignment_3; }

		//INT
		public RuleCall getGreenINTTerminalRuleCall_3_0() { return cGreenINTTerminalRuleCall_3_0; }

		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }

		//blue=INT
		public Assignment getBlueAssignment_5() { return cBlueAssignment_5; }

		//INT
		public RuleCall getBlueINTTerminalRuleCall_5_0() { return cBlueINTTerminalRuleCall_5_0; }

		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	
	
	public class LabelAlignmentElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.LabelAlignment");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLeftEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLeftLeftKeyword_0_0 = (Keyword)cLeftEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCenterEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCenterCenterKeyword_1_0 = (Keyword)cCenterEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cRightEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cRightRightKeyword_2_0 = (Keyword)cRightEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum LabelAlignment:
		//	left | center | right;
		public EnumRule getRule() { return rule; }

		//left | center | right
		public Alternatives getAlternatives() { return cAlternatives; }

		//left
		public EnumLiteralDeclaration getLeftEnumLiteralDeclaration_0() { return cLeftEnumLiteralDeclaration_0; }

		//"left"
		public Keyword getLeftLeftKeyword_0_0() { return cLeftLeftKeyword_0_0; }

		//center
		public EnumLiteralDeclaration getCenterEnumLiteralDeclaration_1() { return cCenterEnumLiteralDeclaration_1; }

		//"center"
		public Keyword getCenterCenterKeyword_1_0() { return cCenterCenterKeyword_1_0; }

		//right
		public EnumLiteralDeclaration getRightEnumLiteralDeclaration_2() { return cRightEnumLiteralDeclaration_2; }

		//"right"
		public Keyword getRightRightKeyword_2_0() { return cRightRightKeyword_2_0; }
	}

	public class GradientDirectionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.GradientDirection");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cObliqueEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cObliqueObliqueKeyword_0_0 = (Keyword)cObliqueEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLefttorightEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLefttorightLefttorightKeyword_1_0 = (Keyword)cLefttorightEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cToptobottomEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cToptobottomToptobottomKeyword_2_0 = (Keyword)cToptobottomEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum GradientDirection:
		//	oblique | lefttoright | toptobottom;
		public EnumRule getRule() { return rule; }

		//oblique | lefttoright | toptobottom
		public Alternatives getAlternatives() { return cAlternatives; }

		//oblique
		public EnumLiteralDeclaration getObliqueEnumLiteralDeclaration_0() { return cObliqueEnumLiteralDeclaration_0; }

		//"oblique"
		public Keyword getObliqueObliqueKeyword_0_0() { return cObliqueObliqueKeyword_0_0; }

		//lefttoright
		public EnumLiteralDeclaration getLefttorightEnumLiteralDeclaration_1() { return cLefttorightEnumLiteralDeclaration_1; }

		//"lefttoright"
		public Keyword getLefttorightLefttorightKeyword_1_0() { return cLefttorightLefttorightKeyword_1_0; }

		//toptobottom
		public EnumLiteralDeclaration getToptobottomEnumLiteralDeclaration_2() { return cToptobottomEnumLiteralDeclaration_2; }

		//"toptobottom"
		public Keyword getToptobottomToptobottomKeyword_2_0() { return cToptobottomToptobottomKeyword_2_0; }
	}
	
	private final SiriusFileElements pSiriusFile;
	private final SiriusFileBodyElements pSiriusFileBody;
	private final QualifiedNameElements pQualifiedName;
	private final QualifiedNameWithWildcardElements pQualifiedNameWithWildcard;
	private final ImportElements pImport;
	private final DesignerElements pDesigner;
	private final ViewpointElements pViewpoint;
	private final RepresentationElements pRepresentation;
	private final DiagramElements pDiagram;
	private final LayerElements pLayer;
	private final MappingElements pMapping;
	private final ContainerElements pContainer;
	private final ConditionalContainerStyleDeclarationElements pConditionalContainerStyleDeclaration;
	private final StyleElements pStyle;
	private final ContainerStyleElements pContainerStyle;
	private final GradientElements pGradient;
	private final LabelAlignmentElements eLabelAlignment;
	private final GradientDirectionElements eGradientDirection;
	private final PaletteElements pPalette;
	private final ColorElements pColor;
	private final ColorValueElements pColorValue;
	private final RGBElements pRGB;
	private final TerminalRule tDOCUMENTATION;
	private final TerminalRule tID;
	private final TerminalRule tINT;
	private final TerminalRule tSTRING;
	private final TerminalRule tEXPRESSION;
	private final TerminalRule tWS;
	
	private final Grammar grammar;

	@Inject
	public SiriusTextDslGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.pSiriusFile = new SiriusFileElements();
		this.pSiriusFileBody = new SiriusFileBodyElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pQualifiedNameWithWildcard = new QualifiedNameWithWildcardElements();
		this.pImport = new ImportElements();
		this.pDesigner = new DesignerElements();
		this.pViewpoint = new ViewpointElements();
		this.pRepresentation = new RepresentationElements();
		this.pDiagram = new DiagramElements();
		this.pLayer = new LayerElements();
		this.pMapping = new MappingElements();
		this.pContainer = new ContainerElements();
		this.pConditionalContainerStyleDeclaration = new ConditionalContainerStyleDeclarationElements();
		this.pStyle = new StyleElements();
		this.pContainerStyle = new ContainerStyleElements();
		this.pGradient = new GradientElements();
		this.eLabelAlignment = new LabelAlignmentElements();
		this.eGradientDirection = new GradientDirectionElements();
		this.pPalette = new PaletteElements();
		this.pColor = new ColorElements();
		this.pColorValue = new ColorValueElements();
		this.pRGB = new RGBElements();
		this.tDOCUMENTATION = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.DOCUMENTATION");
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.ID");
		this.tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.INT");
		this.tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.STRING");
		this.tEXPRESSION = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.EXPRESSION");
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.obeonetwork.sirius.text.SiriusTextDsl.WS");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.obeonetwork.sirius.text.SiriusTextDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//SiriusFile:
	//	documentation=DOCUMENTATION?
	//	'package' name=QualifiedName
	//	imports+=Import*
	//	body=SiriusFileBody;
	public SiriusFileElements getSiriusFileAccess() {
		return pSiriusFile;
	}
	
	public ParserRule getSiriusFileRule() {
		return getSiriusFileAccess().getRule();
	}

	//SiriusFileBody:
	//	Designer | Representation | Layer | Mapping | Style | Palette;
	public SiriusFileBodyElements getSiriusFileBodyAccess() {
		return pSiriusFileBody;
	}
	
	public ParserRule getSiriusFileBodyRule() {
		return getSiriusFileBodyAccess().getRule();
	}

	//QualifiedName:
	//	ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//QualifiedNameWithWildcard:
	//	QualifiedName '.*'?;
	public QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return pQualifiedNameWithWildcard;
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}

	//Import:
	//	'import' importedNamespace=QualifiedNameWithWildcard;
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	//Designer:
	//	documentation=DOCUMENTATION?
	//	'designer' name=ID ('as' label=STRING)? '{'
	//	viewpoints+=Viewpoint*
	//	'}';
	public DesignerElements getDesignerAccess() {
		return pDesigner;
	}
	
	public ParserRule getDesignerRule() {
		return getDesignerAccess().getRule();
	}

	//Viewpoint:
	//	documentation=DOCUMENTATION?
	//	'viewpoint' name=ID ('as' label=STRING)? '{' ('modelFileExtensions' '=' '[' modelFileExtensions+=STRING (','
	//	modelFileExtensions+=STRING)* ']')? ('icon' '=' icon=STRING)? ('representations' '=' '['
	//	(representations+=[Representation|QualifiedName] (',' representations+=[Representation|QualifiedName])*)? ']')?
	//	'}';
	public ViewpointElements getViewpointAccess() {
		return pViewpoint;
	}
	
	public ParserRule getViewpointRule() {
		return getViewpointAccess().getRule();
	}

	//Representation:
	//	Diagram;
	public RepresentationElements getRepresentationAccess() {
		return pRepresentation;
	}
	
	public ParserRule getRepresentationRule() {
		return getRepresentationAccess().getRule();
	}

	//Diagram:
	//	documentation=DOCUMENTATION?
	//	initialized?='@Initialized'?
	//	showOnStartup?='@ShowOnStartup'?
	//	enablePopupBars?='@EnablePopupBars'?
	//	'@MetamodelUris'+ '({'
	//	metamodelUris+=STRING (',' metamodelUris+=STRING)*
	//	'})'
	//	'diagram' name=ID ('as' label=STRING)? 'for' domainClass=STRING ('?' precondition=EXPRESSION)? '{' ('documentation'
	//	'=' endUserDocumentation=STRING)? ('titleExpression' '=' titleExpression=EXPRESSION)? ('rootExpression' '='
	//	rootExpression=EXPRESSION)? ('defaultLayer' '=' defaultLayer=[Layer|QualifiedName])? ('additionalLayers' '=' '['
	//	(additionalLayers+=[Layer|QualifiedName] (',' additionalLayers+=[Layer|QualifiedName])*)?
	//	']')?
	//	'}';
	public DiagramElements getDiagramAccess() {
		return pDiagram;
	}
	
	public ParserRule getDiagramRule() {
		return getDiagramAccess().getRule();
	}

	//Layer:
	//	documentation=DOCUMENTATION?
	//	'layer' name=ID '{' ('icon' '=' icon=STRING)?
	//	'mappings' '=' '[' (mappings+=[Mapping|QualifiedName] (',' mappings+=[Mapping|QualifiedName])*)?
	//	']'
	//	'edges' '=' '[' ']'
	//	'}';
	public LayerElements getLayerAccess() {
		return pLayer;
	}
	
	public ParserRule getLayerRule() {
		return getLayerAccess().getRule();
	}

	//Mapping:
	//	Container;
	public MappingElements getMappingAccess() {
		return pMapping;
	}
	
	public ParserRule getMappingRule() {
		return getMappingAccess().getRule();
	}

	//Container:
	//	documentation=DOCUMENTATION?
	//	list?='list'? 'container' name=ID ('as' label=STRING)? 'for' domainClass=STRING 'style'
	//	style=[ContainerStyle|QualifiedName] ('?' precondition=EXPRESSION)? '{' ('semanticCandidatesExpression' '='
	//	semanticCanditatesExpression=EXPRESSION)?
	//	conditionalStyles+=ConditionalContainerStyleDeclaration*
	//	'}';
	public ContainerElements getContainerAccess() {
		return pContainer;
	}
	
	public ParserRule getContainerRule() {
		return getContainerAccess().getRule();
	}

	//ConditionalContainerStyleDeclaration:
	//	'style' style=[ContainerStyle|QualifiedName] 'if' conditionalStyleExpression=EXPRESSION;
	public ConditionalContainerStyleDeclarationElements getConditionalContainerStyleDeclarationAccess() {
		return pConditionalContainerStyleDeclaration;
	}
	
	public ParserRule getConditionalContainerStyleDeclarationRule() {
		return getConditionalContainerStyleDeclarationAccess().getRule();
	}

	//Style:
	//	ContainerStyle;
	public StyleElements getStyleAccess() {
		return pStyle;
	}
	
	public ParserRule getStyleRule() {
		return getStyleAccess().getRule();
	}

	//ContainerStyle:
	//	Gradient;
	public ContainerStyleElements getContainerStyleAccess() {
		return pContainerStyle;
	}
	
	public ParserRule getContainerStyleRule() {
		return getContainerStyleAccess().getRule();
	}

	//Gradient:
	//	documentation=DOCUMENTATION?
	//	'gradient' direction=GradientDirection name=ID 'from' backgroundColor=[Color|QualifiedName] 'to'
	//	foregroundColor=[Color|QualifiedName] '{' ('label' labelAlignment=LabelAlignment labelExpression=EXPRESSION 'in'
	//	labelColor=[Color|QualifiedName])? ('border' 'size' '=' borderSize=INT 'in' borderColor=[Color|QualifiedName])?
	//	('icon' '=' icon=STRING)? ('heightComputationExpression' '=' heightComputationExpression=EXPRESSION)?
	//	('widthComputationExpression' '=' widthComputationExpression=EXPRESSION)?
	//	'}';
	public GradientElements getGradientAccess() {
		return pGradient;
	}
	
	public ParserRule getGradientRule() {
		return getGradientAccess().getRule();
	}

	//enum LabelAlignment:
	//	left | center | right;
	public LabelAlignmentElements getLabelAlignmentAccess() {
		return eLabelAlignment;
	}
	
	public EnumRule getLabelAlignmentRule() {
		return getLabelAlignmentAccess().getRule();
	}

	//enum GradientDirection:
	//	oblique | lefttoright | toptobottom;
	public GradientDirectionElements getGradientDirectionAccess() {
		return eGradientDirection;
	}
	
	public EnumRule getGradientDirectionRule() {
		return getGradientDirectionAccess().getRule();
	}

	//Palette:
	//	documentation=DOCUMENTATION?
	//	'palette' name=ID '{'
	//	colors+=Color*
	//	'}';
	public PaletteElements getPaletteAccess() {
		return pPalette;
	}
	
	public ParserRule getPaletteRule() {
		return getPaletteAccess().getRule();
	}

	//Color:
	//	'color' name=ID '=' value=ColorValue;
	public ColorElements getColorAccess() {
		return pColor;
	}
	
	public ParserRule getColorRule() {
		return getColorAccess().getRule();
	}

	//ColorValue:
	//	RGB;
	public ColorValueElements getColorValueAccess() {
		return pColorValue;
	}
	
	public ParserRule getColorValueRule() {
		return getColorValueAccess().getRule();
	}

	//RGB:
	//	'rgb(' red=INT ',' green=INT ',' blue=INT ')';
	public RGBElements getRGBAccess() {
		return pRGB;
	}
	
	public ParserRule getRGBRule() {
		return getRGBAccess().getRule();
	}

	//terminal DOCUMENTATION:
	//	'/ **'->'* /';
	public TerminalRule getDOCUMENTATIONRule() {
		return tDOCUMENTATION;
	} 

	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return tID;
	} 

	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return tINT;
	} 

	//terminal STRING:
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return tSTRING;
	} 

	//terminal EXPRESSION:
	//	'"' ('\\' . | !('\\' | '"'))* '"';
	public TerminalRule getEXPRESSIONRule() {
		return tEXPRESSION;
	} 

	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return tWS;
	} 
}
